### ISSUE TITLE
Receiving Ajax error when filtering Name for Manage Existing Employee Shares

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1000]
On page Manage Existing Employee Shares, select Search Criteria as **Employee Name** and enter any invalid text in the Search Text field such as '0001818', 'apple' and hit the 'Filter' button
Expected result: Display error message 'No data available in table' in the table when there is no matching data

Issue noticed for HR and Sys admin
Users: 
Travis Clark - HR admin
Mark Bakusko - Sys admin
![Screenshot 2023-06-14 at 11.59.25 PM (2).png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/4011ddbf-7f50-402f-9c7a-5fbcea7a0e22)![Screenshot 2023-06-14 at 11.59.25 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/9b461a62-326a-4123-a4c9-8697b5a32249)

**Comment by telusdcinco** [comment]
Fixed in #637.

**Comment by steffipravasi** [comment]
@telusdcinco Seems like the issue still persist for Manage Existing Employees Share page![Screenshot 2023-06-21 at 3.09.13 PM copy.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f719326c-a6f9-4445-98c5-7444331f92cb)

**Comment by steffipravasi** [comment]
Issue has been addressed and validated on test. 
Moving for PO review![Screenshot 2023-06-21 at 5.05.56 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/2f38fd8e-e714-42e7-a0b0-d0aeccd3159a).
