### ISSUE TITLE
Duplicate entries and profiles displayed for same user record

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1080]

**Comment by telusdcinco** [comment]
This issue resolved by #857.
The multi-job employee will continue to be displayed in both jobs, may be in different lists (by org).

The duplication was due to #1033 changes that only creates 1 row of next conversation due date for those with multi-job.

**Comment by telusdcinco** [comment]
Run View updates in #857.

Run php artisan command:PopulateUsersAnnexTable > storage/logs/PopulateUsersAnnexTable;

**Comment by steffipravasi** [comment]
@telusdcinco Issue still occurring on Test. Examples:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmlRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ec513aff198d25b79c32c3cb50d32c4a94b94ceb/Screenshot%202023-09-12%20at%201.32.00%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcm1RIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6d1e08dbf239803b520fd2d8f091f92226258605/Screenshot%202023-09-12%20at%201.31.07%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc09RIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9d4049829c6fa70adb49b32faf835a24418ebbbe/Screenshot%202023-09-12%20at%201.30.43%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjZRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f4657389e8929e2567354e5c2ec7739bf94cf98d/Screenshot%202023-09-12%20at%201.30.05%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcitRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bf3a6a0c2b657612fa7a94c73be150611501a97d/Screenshot%202023-09-12%20at%201.29.52%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0dRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1489d802a7c5aa93da883e55e078acaa2a242ac7/Screenshot%202023-09-12%20at%201.29.26%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3FRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6ced789d345de499e89049b1eb8dddbc36996c47/Screenshot%202023-09-12%20at%201.29.09%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3VRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--98445adbf616a6dc3fe567f503a8edaec5abb1cf/Screenshot%202023-09-12%20at%201.28.48%20PM.png)

**Comment by steffipravasi** [comment]
Verified on test. Couldn't find the duplicate entries on the test env. 
There are users with duplicate emp ids, name, email and position but different reports to name. 

Pushing the ticket for PO review.
