### ISSUE TITLE
Stats and Reporting > Next Conversation Due graph is unreadable

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1197]
In both Sys and HR Admin views, the legend at the bottom for the Next Conversation Due graph overlaps with the content and makes it impossible to read some of the text. Can we please reformat to make it clearer? Thanks!

<img width="748" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGUzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1413be859200206fdbffc208b53130ca0c930697/image.png" alt="image.png" />

**Comment by steffipravasi** [comment]
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTI4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--428c8538c5fc028908d02f9e51d20d88202a8a83/Screenshot%202024-01-11%20at%2011.29.43%E2%80%AFAM.png" alt="Screenshot 2024-01-11 at 11.29.43 AM.png" />

**Comment by telusdcinco** [comment]
@jizhaogit Code change looks good.

**Comment by steffipravasi** [comment]
@jizhaogit Still noticing issue when the numbers are different for the Next Conversation Due chart. Also, noticed the issue in the Open Conversations By Topic. 
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW91QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fc0997d65a9c15f52dc07a95689bf696dce29a1/Screenshot%202024-02-05%20at%208.55.46%E2%80%AFPM.png" alt="Screenshot 2024-02-05 at 8.55.46 PM.png" />
<img width="1404" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXN1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2962eb522a07b13b4ad01d7eace85749f5bc0e43/Screenshot%202024-02-05%20at%208.49.10%E2%80%AFPM.png" alt="Screenshot 2024-02-05 at 8.49.10 PM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTB1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48d7b2260345996f2e689b1b252577813bcaaebf/Screenshot%202024-02-05%20at%208.40.01%E2%80%AFPM.png" alt="Screenshot 2024-02-05 at 8.40.01 PM.png" />

**Comment by jizhaogit** [comment]
Hi Steffi, it is the same situation as #1205 - the fix was only pushed in dev.  i pushed it to test can you please help check again? thanks!

**Comment by steffipravasi** [comment]
@jizhaogit The graphs somehow still does not look fixed. I am in full screen of my laptop with 80% zoom out
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGMxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43ac41aabf590f2067b65c5da363f85c3bf2b0d3/Screenshot%202024-02-06%20at%204.47.45%E2%80%AFPM.png" alt="Screenshot 2024-02-06 at 4.47.45 PM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGcxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb5edb05d70e71dec5a7a69da09bbc32cec39203/Screenshot%202024-02-06%20at%204.47.05%E2%80%AFPM.png" alt="Screenshot 2024-02-06 at 4.47.05 PM.png" />

**Comment by steffipravasi** [comment]
The view for Sys admin is still looking fine but when switched to HR admin, the first row has 3 charts and 2nd row has 2 charts. Can we display the first 2 charts in the first row like Sys admin's view?
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHc4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f14736d7cdef3e685973c42b24469be1a0039e51/Screenshot%202024-02-07%20at%204.02.28%E2%80%AFPM.png" alt="Screenshot 2024-02-07 at 4.02.28 PM.png" />

**Comment by steffipravasi** [comment]
Functionality working as expected now. 
Need to discuss the chart size with Jessica tomorrow
<img width="1450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0U4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a803251dc1a499f998fc22d4ee6c3fcd30fe697/Screenshot%202024-02-07%20at%206.54.10%E2%80%AFPM.png" alt="Screenshot 2024-02-07 at 6.54.10 PM.png" />
