### ISSUE TITLE
Goal Bank > Add Goal to Team Goal Bank: default to no audience

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#1205]
**Current Scenario**

When a supervisor goes to My Goals > Goal Bank > Add Goal to Team Goal Bank modal, the default is that all of their employees are selected (see screenshot below). This means that, when the goal auto saves after 15 minutes, it sends email notifications to all those people. This can cause troubles when the goal is actually not ready to be shared.

**Desired Solution**

Default to having no audience selected to ensure that when the goal is auto saved people are not receiving emails that they shouldn't be. We just have to make sure that, when the supervisor does add audience members, they receive emails at that time (after they have been added).

<img width="834" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a38ccd05455f01dd7ba8e4a1a6a929356de39e3/image.png" alt="image.png" />

**Comment by jizhaogit** [comment]
@telusdcinco Hi Dennis, please help do the code review. thanks!

**Comment by telusdcinco** [comment]
@jizhaogit Code change looks good.

**Comment by steffipravasi** [comment]
@jizhaogit Not sure if the fix for this ticket is deployed to test. The default audience is still the entire list of audience being selected when trying to add a new goal
Req: Default to having no audience selected
<img width="1325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE12QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5443297c27767950b14b7642825828537cc4d25/Screenshot%202024-02-06%20at%2012.08.23%E2%80%AFAM.png" alt="Screenshot 2024-02-06 at 12.08.23 AM.png" />

**Comment by jizhaogit** [comment]
Hi Steffi,  yes you are right..    i pushed it to test.  can you please help check again? thank you!

**Comment by steffipravasi** [comment]
The default audience is removed but I think it will be a good place to work on ticket #1219 to address the following issue: 
Issue: In ticket #1205, we have made the audience list to be unchecked as default. But if the user, for example, checks one employee from the audience list, and leaves the screen. After the auto-save, the dialog box with the auto save message is displayed, and once user clicks on Okay, there is another dialog box with message Goal saved. Once user clicks on Ok, the goal page closes automatically and the emails are sent out without giving the user option to add more audience.

Requirement from the ticket: Default to having no audience selected to ensure that when the goal is auto saved people are not receiving emails that they shouldn't be. We just have to make sure that, when the supervisor does add audience members, they receive emails at that time (after they have been added).

Thus adding a dependency to ticket 1219. Will confirm with Alison or Jessica to move forward.

**Comment by steffipravasi** [comment]
@jizhaogit The desired solution of this ticket is still not met: Default to having no audience selected to ensure that when the goal is auto saved people are not receiving emails that they shouldn't be. We just have to make sure that, when the supervisor does add audience members, they receive emails at that time (after they have been added).
- I created a goal and let it auto-save or Saved manually without closing the goal. The selected audience received email notifications multiple time for the same goal,
- Expected solution: Only once the email notification must be sent even if multiple auto-saves or saving manually. If possible we can send the notifications at the time of closing the goal to avoid this issue:
- <img width="1447" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWZJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4afd54e060fa008263ac10ae44413d6dffad0cf2/Screenshot%202024-03-08%20at%205.11.41%E2%80%AFPM.png" alt="Screenshot 2024-03-08 at 5.11.41 PM.png" />
<img width="1449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ecfe77c7da47486cd8b4a30d59288c0539bc276/Screenshot%202024-03-08%20at%205.11.32%E2%80%AFPM.png" alt="Screenshot 2024-03-08 at 5.11.32 PM.png" />
<img width="301" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f908887c06ce806fcb4b3ffe1492f4988d01648/Screenshot%202024-03-08%20at%205.12.34%E2%80%AFPM.png" alt="Screenshot 2024-03-08 at 5.12.34 PM.png" />

**Comment by jizhaogit** [comment]
@steffipravasi  Thank you! the issue should be addressed. please help verify . thanks!

**Comment by steffipravasi** [comment]
@jizhaogit 
I've added a new goal as a supervisor, but the audience list did not receive notifications(in-app or emails) even after closing the goal. Can't see the notifications being triggered.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXZPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ff6a01773360734ef05ddd5f3384bfab90d93eef/Screenshot%202024-03-11%20at%203.31.40%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 3.31.40 PM.png" />
<img width="1669" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTNPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21764e7b319a58bcc27c72068b3a452361f83ee4/Screenshot%202024-03-11%20at%203.32.55%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 3.32.55 PM.png" />

**Comment by jizhaogit** [comment]
Hi Steffi, it should be address. thanks!

**Comment by steffipravasi** [comment]
Functionality working as expected
