### ISSUE TITLE
Supervisor is unable to access employee profile through "My Team"

### ISSUE THREAD

**Issue by jessicahjwu** [bcgov/performance#1331]
Emily Drown, EEID#168789, is unable to access her direct reports' profiles via My Team. When she clicks on any of her direct/shared reports name, the page returned with 500 server error message.

<img width="1758" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelBHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3f5ec6b4676d99d1d221bca51bdbab83c832293/image.png" alt="image.png" />
<img width="1608" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemJHQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ebeb776803ac5cd3cfed5debca195a0c88bb18d0/image.png" alt="image.png" />

There had been other users reporting this issue, in which one of them is Emily's direct report, Andrew Ross.

**Comment by telusdcinco** [comment]
Related to fix #1224.  New function is going thru infinite loop when resolving hierarchy manager.  EE 168789 is coming back as manager for EE 168789.  The loop continues until the system runs out of memory.

**Comment by telusdcinco** [comment]
Can be replicated in Dev and Test.

**Comment by telusdcinco** [comment]
Additional code fix for potential issue after introducing employee_demo audits by #

**Comment by steffipravasi** [comment]
The users Emily Drown & Andrew Ross can access the direct/shared reports from My team. Issue has been addressed.

**Comment by jessicahjwu** [comment]
Emily can access Andrew's profile however she's unable to view direct reports of Andrew's, page returned as "you don't have the right permission to access this employee's file"
<img width="1250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNaQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8a449f08ba0004a884e159e989cd8280fbacd737/image.png" alt="image.png" />

Emily as the team leader, should be able to view all employee profiles under her

**Comment by telusdcinco** [comment]
@jizhaogit I may need some help from you to fix remaining issue.

**Comment by steffipravasi** [comment]
@jizhaogit Not able to verify the fix. 
1) Logged in as Emily drown' profile and tried accessing the employees profile through the team members list, but receiving a 504 error for all of them
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUFNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22197c13dd49580bd2321a6d523e6280bca3d1a5/Screenshot%202024-07-25%20at%209.57.04%E2%80%AFAM.png" alt="Screenshot 2024-07-25 at 9.57.04 AM.png" />
2) Also, I have a question why does the user's name itself also appear in the team members list as well as the supervisor?
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33e8dd262051fd1fbf30176811041ec170cb6c11/Screenshot%202024-07-25%20at%209.59.35%E2%80%AFAM.png" alt="Screenshot 2024-07-25 at 9.59.35 AM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThNQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b93050ecdd3b8309bce222859222eedf1b18f1fc/Screenshot%202024-07-25%20at%2010.01.31%E2%80%AFAM.png" alt="Screenshot 2024-07-25 at 10.01.31 AM.png" />

**Comment by jizhaogit** [comment]
Hi @steffipravasi
#1  is solved.
#2  checked with Dennis, this supervisor, Emily is her own supervisor. this is a data issue.

**Comment by steffipravasi** [comment]
@jizhaogit Still facing the same issue,
When Emily tries to access the team member's profile, she is receiving error. For the SS below, tried accessing Andrew' profile
<img width="1422" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e09dc55f8ad6c4350b4826b1f24a072f6a46072b/Screenshot%202024-07-25%20at%2012.36.25%E2%80%AFPM%20%282%29.png" alt="Screenshot 2024-07-25 at 12.36.25 PM (2).png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkFOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db65461e278b17f6cce7148e2a7f9bfea5b084f6/Screenshot%202024-07-25%20at%2012.36.25%E2%80%AFPM.png" alt="Screenshot 2024-07-25 at 12.36.25 PM.png" />

**Comment by steffipravasi** [comment]
Working as expected.
