### ISSUE TITLE
As an HR or System Admin I want to create goals in the goal bank associated with organization or role rather than individual

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#471]
Currently, goals in the goal bank can be created and pushed to any audience based on criteria such as organization (dept ID / org tree), classification (filter on employee list), name, etc. However, once the goal is pushed, it becomes associated with the individuals only rather than any of the other criteria. 

So, for example, as an HR Admin I can create a goal and push it to Corporate Workforce Strategies Branch. However, if a new employee joins the Branch at a later date, they won't see the goal in their Goal Bank; and if an employee leaves the Branch at a later date, the goal will follow them even though it is no longer relevant to their work.

We need this to be more dynamic and to recognize when people change positions and organizations. Suggest the following.

Step 1 - Create Goal

Step 2 - Select Audience
Selection criteria: Organization, Level 1, Level 2, Level 3, Level 4, Classification, Job Title, Employee ID (any combination of these elements).

Each selection criteria is stored with the goal in the Goal Bank. When user logs on, the system compares user info against goal selection criteria and displays relevant goals in the Goal Bank for that user. If the user does not match all selection criteria, they do not see the goal.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Is this something we could assign to Ji?

**Comment by telusdcinco** [comment]
Deployed to Dev, as part of #350.  Only Sys Admin for now, pending HR Admin.

**Comment by telusdcinco** [comment]
Integration of Dept selection on the Add New page is taking longer.  Work around right now is that the Edit Goal for BUs is available and working.

**Comment by telusdcinco** [comment]
Completed changes for both Sys Admin and HR Admin
- Auto Filter (keypress/tab out/click/dropdown select)
- Fixed filter bug using criteria/search text (also applied to other HR/Sys admin pages using criteria/search text)

**Comment by Travis-A-Clark** [comment]
@telusdcinco I logged in as Sys Admin, created a goal and assigned by business unit to all of the BC Public Service Agency. It isn't showing up in any of the employee goal banks.

Assigning by individual appears to work. But not by business unit. Thoughts?

**Comment by Travis-A-Clark** [comment]
@telusdcinco Still having issues with this. Perhaps we can run through it at our 1pm. Thanks!

**Comment by Travis-A-Clark** [comment]
@telusdcinco I created a goal "Business Unit Test - July 11" and assigned it to Public Service Agency > People and Organizational Development > Corporate Workforce Strategies. It says it has been assigned to 13 people in the business unit audience, but it is not showing up in any of their My Goals > Goal Bank areas.
<br>

I created a goal "Individual Goal Test - July 11" and assigned it to the 13 people that work in Corporate Workforce Strategies. It processed for a long time and then timed out with the 504 error. When I reloaded the page it had assigned the work goal to over 29,000 people in the individual audience.
<br>

It doesn't appear that either way is currently working. Let me know if you want to chat.

**Comment by Travis-A-Clark** [comment]
@telusdcinco It looks like the issue with creating the individual goal was that I selected the all check box at the top of the audience table. I had filtered the table so that only 13 employees were visible, but selecting the all check box seems to have defaulted to selecting all BC Public Service employees, not just the ones I filtered.
<br>

Also found that the suggested/mandatory options are not working. It always shows up as suggested, even when I create it as mandatory. Can you double check? And if possible, remove the "Any" default option and just have it default to "Suggested" with the drop down available to switch it to "Mandatory" if required.

**Comment by telusdcinco** [comment]
Goal Bank created/shared with BU specific audience now shows to impacted employees.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Still not working for me. Logged in as Jennifer Erickson, created BU Test - July 14 and assigned to Corporate Workforce Strategies. Logged in as Travis Clark, don't see it in my goal bank.

**Comment by telusdcinco** [comment]
Redeployed files missed earlier.  Looked at other users in Dev within the same team and the banked goals created by admins are now showing.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Looks like it is showing up now. Excellent! Only odd thing is that I am creating the goal as Jennifer Erickson (Sys Admin) and it is showing up in my list as being created by Travis Clark. When I log in as Adonica Sweet it shows as being created by Adonica. It is saying that the user that is logged in is the one that created it rather than Jen who actually did. Can you take a look?
<br>

Getting so close!

**Comment by telusdcinco** [comment]
Issue resolved, change pushed to Dev.  Issue only for Supervisor created goals.  The admin bank goals shows the Created By name.
Please note Adonica is both the tagged in Goal's User ID and Created By ID, which will not be a good test case to show that the issue is fixed.  Please use another Supervisor to create a new goal to test in Dev.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Reviewed in Dev.  Goals created by Sys Admin now show with correct "created by" info. Goals created by supervisor are show a blank in the "created by" column, See below.
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/def090d7-4864-4187-8a64-f67954d0c64a)

**Comment by telusdcinco** [comment]
Created by column now populated when Supervisor creates a new goal in My Goals>Goal Bank.
Pushed changes to Dev for testing/verification.

**Comment by Travis-A-Clark** [comment]
@telusdcinco Looks good in Dev. Thanks!
