### ISSUE TITLE
Shared Function Fixes - June 2022

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#489]
Scenario: Travis Clark is shared with Tanya Mackay. Tanya now sees Travis on her My Team page and on her My Conversations page as an optional conversation participant. However, Tanya does not have the "Conversations with My Team" list on her Open and Completed Conversations tabs. We need to add this portion when an employee is shared with someone, the same way that we add the "My Team" navigation item.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c37e945c-015b-42b1-ac5b-caff301f594c)

**Comment by jizhaogit** [comment]
fix deployed in dev

**Comment by Travis-A-Clark** [comment]
@jizhaogit I see that has been implemented on the "Open Conversations" tab but I still don't see the additional area for Conversations with my Team on the "Closed Conversations" tab. Can you please add there as well? Thanks!

**Comment by jizhaogit** [comment]
updates are deployed in dev
