### ISSUE TITLE
My Goals > Goal Bank - Design 2.0

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#620]
**Description**
Remove the goal cards and update to "list view" more consistent with the top half of the page. Columns to include: Goal Title, Goal Type, Tags, Date Added, Suggested/Mandatory, Audience drop down, Action items edit/delete.

**Designs**
![My Goals _ Goal Bank-2.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/5c86b9ad-3df4-445a-a0d1-0a177cc68156)
![My Goals _ Goal Bank.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/614a8b10-d77f-485c-b75e-04a002c58ab3)
![My Goals _ Goal Bank-1.jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/b91fded6-4510-45f5-92d0-66a3e5ce9956)

**Comment by Travis-A-Clark** [comment]
@jchow11 I really like the concepts to save space. The filters/search for the Team Goal Bank area won't need a "Created By" option since all goals listed here will have been created by the same user/supervisor that is logged in. We will also need a Tags column in the table display (already exists in the current My Goal Bank). Everything else looks good!

**Comment by jchow11** [comment]
@Travis-A-Clark designs updated and attached to ticket!

**Comment by jizhaogit** [comment]
@Travis-A-Clark I can see it is a very difference between the new goal bank design with all other pages of PDP, for example, the page title place, user's profile picture in the right side corner, etc., can you please verify it we want to use this design for our current spring? thanks!

**Comment by Travis-A-Clark** [comment]
@jizhaogit Please ignore those differences and focus on the changes to the specific page in the My Goal Bank and Team Goal Bank areas. The overall design and page layout stays the same. Thanks!

**Comment by steffipravasi** [comment]
1) Cursor does not change from arrow to hand when hovered anywhere in both section
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Steffi%20-%20Testing/Screen%20Recording%202023-05-17%20at%2011.14.03%20AM.mov?csf=1&web=1&e=x5CrMF
2) Aligning the title and text
![Screenshot 2023-05-17 at 11.15.37 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/fd690bc2-6bbe-431c-9129-f066382595b8)
3) Typo error
![Screenshot 2023-05-17 at 11.17.50 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6007ebb6-9feb-4539-a270-e408556fc064)

**Comment by steffipravasi** [comment]
@Travis-A-Clark The action item buttons for Team Goal Bank goes out of the frame because of the large number of columns in the table. Ji indicated that there's nothing much we can do about it except removing any one column. How should we proceed?
![Screenshot 2023-05-18 at 5.39.29 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3c33a78a-9663-470e-9f67-27a599aa8121)![Screenshot 2023-05-18 at 5.38.40 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6ea80f84-3210-4156-a2cc-e4abd3ff0eb0)

**Comment by steffipravasi** [comment]
@jizhaogit 
1) Please remove the Created by field from Team Goal Bank
2) As discussed, Add the Display name to the created by column if available
3) Look into the missing user from the created by drop-down menu
User: Chad Hoskins has a goal from Muhammad Ali, but cannot see him in the drop-down
4) Display the individual tags in each line to solve the problem of action buttons going out of the frame.

**Comment by steffipravasi** [comment]
Action buttons displaying out of the frame issue is resolved.

**Comment by jizhaogit** [comment]
goal id 764   display_name justice org  not show in ddl
	797		   DisplayName_May18  not show in ddl
	787	           Justice_Goal


only this issue still need to take look others should be good.

**Comment by jizhaogit** [comment]
issue addressed

**Comment by steffipravasi** [comment]
@jizhaogit 
Once a filter is applied to the Created By field, the other options from the drop-down list are hidden. Can we show all the options regardless of search applied
Before applying the search:
![Screenshot 2023-05-23 at 12.20.27 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b462a471-8207-4ad3-8169-24ac3298d13c)
After search applied: 
![Screenshot 2023-05-23 at 12.20.36 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6aea628f-00da-4245-b25d-343a11d2ae19)

**Comment by jizhaogit** [comment]
@steffipravasi   i checked the code for the tags, found that in the "My Goal Bank" list we were using comma to separate tags. But based on our last discussing about the "Team Goal Bank"  list we are currently using line break for each tag. for sync the whole page, i modified the "My Goal Bank" list as same as "Team Goal Bank".   Thanks!

The filter for created by is corrected too.

**Comment by steffipravasi** [comment]
Issue addressed and validated on test.
The Created by list remains intact regardless of the filters applied. 
Ticket ready for PO review.

**Comment by telusdcinco** [comment]
@steffipravasi 
Added a fix to resolve My Goals>Goal Bank for goals having more than 1 tags will display twice causing issue for changes implemented in #785.
