### ISSUE TITLE
My Conversations > Open Conversations - Design 2.0

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#623]
Primary changes:

- Create separate accordion sections for Instructions, Conversations with My Supervisor, and Conversations with my Team
- Add indication of who has signed each conversation to the list view
- Update search functionality
- Add pagination (10 item limit) to each accordion list so that the user can move between pages within the accordion when they have large numbers of open conversations.

**Designs**
![My Conversations _ Open Conversations (collapsed).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/19ae8d9c-4745-4425-9c74-196bb6520ff3)
![My Conversations _ Open Conversations _ Conversations with my supervisor (Expanded).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/70b616c4-9a65-43c5-abe2-624a353179b8)
![My Conversations _ Open Conversations _ Conversations with my team (Expanded).jpg](https://images.zenhubusercontent.com/61e98ff375d0505e601dd00e/b4670723-b305-4f25-80c6-e00f2ffbc9ef)

**Comment by Travis-A-Clark** [comment]
@jchow11 I don't see any images on this thread. Can you please re-attach? Thanks!

**Comment by jchow11** [comment]
@Travis-A-Clark updated!

**Comment by Travis-A-Clark** [comment]
@jchow11 I like the overall design here as well. Space saving and easier to sort through as the lists grow over the years. I think we can remove the "Date" column and search option for Open Conversations. That info is important for Completed Conversations, but open conversations could take place over days or weeks so I don't want to confuse things by associating only one date with them.

Also just a note that we will have to incorporate the "Next performance conversation is due..." information in these designs as well.

Thanks!

**Comment by Travis-A-Clark** [comment]
@jchow11 Just nudging for the updated design with the few changes noted above so we can put these over to the Dev side. Same for ticket #620. Thanks!

**Comment by jchow11** [comment]
@Travis-A-Clark designs updated and attached to ticket!

**Comment by steffipravasi** [comment]
1) Can we reduce the white space between the subtext and the title, and also remove the grey top border from both sections? Can we do the same for the Conversation Templates page too? 
![Screenshot 2023-04-20 at 2.05.16 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/396ea9c9-c37f-48fd-914e-701b641364e2)

**Comment by jizhaogit** [comment]
@steffipravasi Most of the issues are addressed except the following:

#1 Can we reduce the white space between the subtext and the title, and also remove the grey top border from both sections? Can we do the same for the Conversation Templates page too?
**The page elements gap is controlled by the Bootstrap framework. We can special some of them but since it will need to manually adjust the pixel of the element location that may cause the layout to be different in different sizes of monitors and browsers.  Please let me know if we still need to adjust especially on this page.**

#4 When any filter is added to the search fields, it seems like the page is refreshed and the user is been navigated to the top of the page and have to scroll back down to the Team section.
Expected: User should stay in the my team section regardless of the filers added
**The filter element change will submit the form to do the searching process. That will cause the page to be reloaded. i didn't find a good way to re-locate the page anchor but will try to see if we can jump to the anchor after the form submitted**

#5 Can we sort the Team Members list from a-Z
**the conversations are sorted by their create time.  and after we applied dataTable for the data listing you can always sort the data by any columns you like.** 

#9 The expanded section minimizes itself when a conversation is deleted. Can we keep the expanded section option until user minimizes itself. Occurring for both section.
**same issue as #4**

#13 Can we align the arrows to the center of height for each section. Can we do the same for Conversation
**We cannot align the arrows to the center of the section because we cannot control how height each setction will be.  So i align the arrow ALWAY be the same height with the section's first row. Please let me know if it works.**

**Comment by steffipravasi** [comment]
1-Issue can be ignored
2-Pass
3-Pass
**4- Not fixed yet**
**5-Will confirm with Travis**
**6-Fail**
**7-Fail(still missing the tab highlighting)**
8-Pass
**9-Not fixed yet**
**10-Fail**
![Screenshot 2023-04-25 at 5.54.38 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/326164e6-d1bc-4582-9594-d34a45ebdca3)
11-Pass
12-Pass
13-Issue to be ignored

Added some more issues:
14) Cannot open the conversations now by clicking on the title
15) Can we align these elements
![Screenshot 2023-04-25 at 6.07.35 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/25436215-7d76-4cb6-b58d-70a2233541b7)
16) Alignment of elements changes when a filter is applied
![Screenshot 2023-04-25 at 6.21.46 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/f92e1feb-84a4-451a-8e36-ebae04595c9c)

**Comment by jizhaogit** [comment]
The following issues are addressed in test
6-Fail 
Once any filter is applied to the My Team and then tried to minimize the Conversation with My Team section, the results still appear at the bottom and won't let the user minimize.

7-Fail(still missing the tab highlighting)
When a filter is added, the selection of tab 'Open Conversation' on the top is removed

10. Filtering the columns with Employee Signed and Supervisor signed doesn't work when value 'No' is selected.

**Comment by jizhaogit** [comment]
@steffipravasi @Travis-A-Clark i will move this ticket to in test time line for now since the main issues are addressed and others if you have questions we can talk. thanks

**Comment by steffipravasi** [comment]
@jizhaogit 
As discussed, we need to fix the following parts:
6 - Please change the arrow to facing downwards when minimized. This same needs to be applied to Completed conversations both for supervisor and team members
![Screenshot 2023-04-28 at 2.33.23 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/ccb3bec4-7954-490e-8112-a022dddd5ab4)
7 - The tab below needs to be highlighted when filters are applied. This same needs to be applied to Completed conversations both for supervisors and team members![Screenshot 2023-04-28 at 2.36.29 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/93f1e6eb-5835-4580-831d-517d0cddc482)![Screenshot 2023-04-28 at 2.37.52 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/61e9fb7d-7492-4429-9526-e3581968812a)
10 - Can see Yes even when No is filtered for supervisor and employee
![Screenshot 2023-04-28 at 2.38.33 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/76dc62b4-1ecb-42d8-9032-59a6090f0b02)
14) Cannot open the conversations now by clicking on the title
-----------------------------------------
We will be discussing the other issues with Travis on monday

**Comment by steffipravasi** [comment]
6 - Pass, 7-Pass, 14 - Pass
I am still noticing these issues:
10 - Fail
Can see Yes even when No is filtered for supervisor and employee
![Screenshot 2023-05-01 at 10.41.37 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8c53a2af-42f8-461e-b08d-f2044bde3f21)
15) When a conversation is opened, tried to maximize and minimize the Preparing and Suggested sections from the modal and noticed that the action is affecting the page in the background where the Conversations with My Supervisor and Team opens and closes. Also, lets keep the 'Preparing' and 'Suggested' sections minimized when a conversation is opened. 
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Testing1/623.mov?csf=1&web=1&e=3mkfe4
16) Noticed an extra sort filter on the right for My Supervisor and My Team
![Screenshot 2023-05-01 at 10.48.42 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/33108411-73bd-4304-9c8e-0facc7a57b44)
17) Team members list has employees who are not listed in My Team User: Paula Milum
![Screenshot 2023-05-01 at 11.28.44 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/dd8fa761-7ca5-47d1-91bf-2458f3dc0cb4)
Also, newly shared team member is not displayed in the Team members lst

**Comment by jizhaogit** [comment]
@steffipravasi I will put this ticket in the dev time line but please test it with #484 because as we discussed they are all related to each other. thanks!

**Comment by steffipravasi** [comment]
Test validated. Issue 10,15,16,17 - Pass

**Comment by Travis-A-Clark** [comment]
Can we please add the search filters to Conversations with my Supervisor area as well? Thanks!

**Comment by steffipravasi** [comment]
@jizhaogit This issue still persist for the completed conversation that the search fields are affecting each other. Searched for conversation type Onboarding for supversisor but see the results in my team too and vice versa.
![Screenshot 2023-05-03 at 1.35.04 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/994194ec-6f71-43c1-b2db-dc4ef1c7ba1f)
Since, we are adding the search fields in open conversations also, hoping that we add the code to fix this issue there too.

**Comment by jizhaogit** [comment]
@steffipravasi below are the details of the update:
1. filter is applied in open conversation's supervisor list
2. participants header is added in template performance-checkin item
3. filter in both open/complete conversations page are now fixed will not effect each other

**Comment by steffipravasi** [comment]
@jizhaogit I have also noticed this issue where if I open a conversation, there are extra contents displayed in the modal eg; additional comments and sign-off sections. They disappear after 2-3 seconds of flashing. And another is when that conversation is closed, the Conversation with My Supervisor or team section minimizes itself as if the page has ben refreshed. 
https://bcgov.sharepoint.com/:v:/r/teams/02915/Shared%20Documents/Product%20Team/Testing1/623(1).mov?csf=1&web=1&e=CSKe7K

**Comment by jizhaogit** [comment]
updated below:
1. The Supervisors search field in Oepn conversations with Supervisor is not showing accurate results. There are 4 conversations with Travis but only shows 2. - **fixed**
2. The Completed conversations with the supervisor's search fields - Conversation type and Supervisor are affecting the conversations with my team.  - **fixed**
3. Is it possible to align the Name title with the column text    -  **fixed**
4. The date search field in Completed conversations with the supervisor and my team is not working as expected   -  **fixed**


@jizhaogit I have also noticed this issue where if I open a conversation, there are extra contents displayed in the modal eg; additional comments and sign-off sections. They disappear after 2-3 seconds of flashing. And another is when that conversation is closed, the Conversation with My Supervisor or team section minimizes itself as if the page has been refreshed
1. about the extra content displayed:      it is because the js layout control needs to take effect after the page is ready.
2. once you close the conversation and trigger the conversation updated, the page will be submitted.  that will refresh the whole page.

**Comment by steffipravasi** [comment]
Test validated. 
Issue 1,2,3,4 - Pass
As per Ji's comment, the content flashing and section minimizing cannot be fixed. 
Ticket ready for PO review.
