### ISSUE TITLE
HR/Sys Admin > Goal Bank: create notification when a new individual or business unit is added to an existing goal

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#700]

**Comment by jp-Telus** [comment]
Found a way to determine the newly insert employees or organizations during the update operation, 

Work Done
1. New model created for the existing table goals_shared_with  (Model called GoalSharedWith)
2. Update the existing Model -- added the fillable and goal() function.
3. Updated both GoalBankController in HRAdmin and SYSAdmin area 
4. Home page (DashbaordNotification) added for newly insert employees 
5. Email notification will sent out for newly insert employees when the following condition are matched
    a. email configuration on the system level is 'on' (PRCS_EMAIL_NOTIFICATION=on) in .env file  
    b. the 'allow email message' is Yes on the remployee's organization (defined in the Access Organization under System security).  
    c. the user's system preference is Yes on "Adds a new goal to my goal bank"

**Comment by Travis-A-Clark** [comment]
@jp-Telus Please confirm if the process is behaving as expected in the Dev environment. If so, please push to Test so that Steffi can review. Thanks!

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Yes, I did some test scenarios on the DEV region this morning. Worked as expected:

_My test case_ 
1. Create a new Goal Bank  for one business unit, 
    BC Public Service Agency > Corporate Services	Business Performance > Data & Insights
2, login as user (Glen.Seredynski@gov.bc.ca) who is in the organization which I will add by update function, enable the user preference to enable the Goal Bank message
3. Update newly created Goal Bank with the new business unit 
    BC Public Service Agency > People and Organizational Development > Strategy Management Office
4. Check the Notification log to see whether the email sent, 

Test Result:  Yes,  worked as expected, only 1 email sent.

Note: there is an issue when I update by specify "Individual" in DEV region but not on my local. the error 

`Too few arguments to function App\Http\Controllers\HRAdmin\GoalBankController::updategoalone(), 1 passed in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php on line 54 and exactly 2 expected
`

I have requested to migrate to TEST region. The above issue may just happen in DEV only. Thank you.

**Comment by steffipravasi** [comment]
@jp-Telus The test site is giving a 500 server error when I am trying to add a goal through System Admin -> Goal Bank for a business unit
User: sysadmin1@example.com, pswd: sysadmin1@2022![Screen Shot 2022-09-06 at 10.48.26 AM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/b047ec5d-6634-4aba-a756-767f6ec9ea91)

**Comment by Travis-A-Clark** [comment]
@jp-Telus Yes, that works for me. Thanks!

**Comment by jp-Telus** [comment]
Migrated to TST with dependence  #636

**Comment by steffipravasi** [comment]
Env: Test
1) Test case: Goal added by sysadmin, Goal name: WorkGoalTesting, Updated individual: Achari,Jaivin
Email received but there is one error, the name of the recipient must be displayed after word Hello, but right now the id of the user is shown.
![Screen Shot 2022-09-14 at 3.29.32 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/9287896c-90c7-4823-94e5-780150be6f9c)

**Comment by jp-Telus** [comment]
Item 1 and 3 were resolved and the name was display correctly.
Item 2, there is no email send out since the 'BC Pernsion Corp" is not allow login in the access organizations page.
Item 4: No sure the problem and trouble to replicate in the local region.

**Comment by steffipravasi** [comment]
Test fail
Issue number 2 is not fixed.
Users not receiving the email when a new organization is added to an existing goal. Issue is for a sys admin only. works fine when an HR admin creates the same goal type. In-app notifications are received.
Test case: 
i) Login as SysAdmin
ii) Create a new goal in the goal bank and add the organization BC Public Service Agency
iii) Go to Manage Goals in Goal Bank
iv) Find the added goal and select it
v) Add Advanced Education and Skills Training organization to the goal
vi) Expected results is that the employees in Advanced Education and Skills Training must receive an email
Actual result is that none of the Advanced Education and Skills Training employee receive an email.
The receive an email in account preference is on and also from the system security. There is no entry in the notification log.

**Comment by jp-Telus** [comment]
@steffipravasi 

Finally, I can replicate your issue on my local region. I did extractly your steps and noticed that only few email sent out but this is much less than my expectation.

I noticed that when the form submit, the submit data  "select_org_nodes" are rare, the input "id"s are not the organization_trees's id, only between 1 to 4250. But the most of the ids are totally difference, greater than 4250. 

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/7b88d6e4-df37-4bf6-97e8-958302145c8f)

@Dennis, when you have time, could you please kindly check the value on "select_org_nodes" before you submit ? Thank you.

**Comment by jp-Telus** [comment]
The previous issues resolved, the selected business unit data were stored correctly on the table. The program updated for creating in-app message :
1. When the new goal added to individual or business, in-app message created 
2. When the new "indivduals" added to the existing goal, the in-app message only created for the newly added individuals by comparing the previous data..
3. When the new "business unit" added to the existing goal, in-app message only created for the employee only newly added by comparing the previous data. 

@Travis, currently, only In-app notification created, do we need the email notification sent out also ? Thanks.

Status: WIP

**Comment by jp-Telus** [comment]
Test done on DEV region 

1. Login as Amy Lee (Amy.Y.Lee@gov.bc.ca), and checked on 'Adds a new goal to my goal bank', and logout

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/21ca9d1c-370f-44a9-80c9-4dffbf9c3e49)

2. Login as SysAdmin1, Add a new Goal and assigned to Amy Lee

3. Verified that both InApp and Email notification sent out 

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/b90b165b-0dac-4e93-9898-fe58a9031769)

**Comment by steffipravasi** [comment]
Test data have setup to test this ticket https://bcgov.sharepoint.com/:w:/r/teams/02915/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B8c43f42e-09c5-403b-9bd7-fbc1da473e0b%7D&wdOrigin=TEAMS-ELECTRON.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1

**Comment by steffipravasi** [comment]
This ticket can be validated once ticket 944 and 945 are fixed as those issues are making testing difficult and its hard to differentiate the notifications.

**Comment by steffipravasi** [comment]
Added employee 000648| Robinson,Caro to goal Growing shareholder value. Caro didn't receive

**Comment by steffipravasi** [comment]
When editing/updating the goal, the pages take time to load and at last gives a 504 server error when the Save Changes button is clicked.

**Comment by steffipravasi** [comment]
Update: Testing blocked due to the errors for Sys and Hr admin

**Comment by steffipravasi** [comment]
@jp-Telus 
Test status: Fail
User: Judy.Harringa@gov.bc.ca	001818, Harringa,Judy K 
belongs to Citizens Services, did not receive any **in-app notification** when 
-a new goal was added to the goal bank
-Citizen Services was added to an existing goal
-Judy was added as an existing goal
Have received the emails though.

**Comment by jp-Telus** [comment]
@steffipravasi 

Finally, found an issue and fixing on my local and pushing to DEV region.

**Comment by steffipravasi** [comment]
Trying to add a new goal through Sys Admin but receiving the Time out error on frond end. Goal is still added in the background.
![Screenshot 2023-05-04 at 5.32.14 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/6ef9fee0-5df0-4c8e-9c2b-2e1d675440db)

**Comment by steffipravasi** [comment]
@telusdcinco 
We receive a 504 Time out error while adding a new goal and updating a goal too for a business unit from the goal bank
![Screenshot 2023-06-01 at 12.00.10 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/3330b12f-c0b4-440f-bf3b-9673802aa3b0)

**Comment by telusdcinco** [comment]
@steffipravasi 
504 error fixed when creating/updating goals for ministries with large employee list.

**Comment by steffipravasi** [comment]
Issues related to this ticket are fixed and validated on Test. 
Others issues related to Goal Bank are addressed in tickets in Product Backlog. 
Moving for PO review.

**Comment by telusdcinco** [comment]
@jp-Telus Just FYI on additional changes for Goal Bank Notifications.
- Employees by inheritance was applied to the notifications
- array chunking of 1000 was applied as the employee list was too big for ministries like Justice (9000+), errors occurring for big lists.
