### ISSUE TITLE
HR/Sys Admin > Reporting and Statistics > Conversation Summary: add column to CSV for due date category

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#725]
The Next Conversation Due dates are grouped as overdue, < 1 week, <1 month, >1 month. Let's add a similar column to the CSV download so that HR Admin can easily filter for those categories in Excel.

Let's also take the opportunity to update the groups to: overdue <1 week, 1 week - 1 month, >1 month.

**Comment by jp-Telus** [comment]
New column called "Due Date Category" were added in the output csv file for both HRADMIN and SYSADMIN. Thanks.

**Comment by Travis-A-Clark** [comment]
@jp-Telus The CSV file looks good. Thanks!

Can we please rename the category currently called "<1 month" to "1 week to 1 month"? I am assuming that is how the logic behind the scenes works: if due date is 7 days away or sooner it is in the <1 week category, and if it is between 8 days and 30 days it is in the 1 week to 1 month category. No overlap between the two, correct?

**Comment by jp-Telus** [comment]
Work done on DEV region for both under HRADMIN and SYSADMIN area, rename the category from '< 1 month ' to '1 week to 1 month' . 

Correct, the program did not overlap between the days when compare

            < 1 week'   ==>                 1 to 7,
            '1 week to 1 month'  ==>  8 to 30
            '> 1 month'  ==>               > 30
        ];
name was

**Comment by Travis-A-Clark** [comment]
@jp-Telus This is now in Production and working as intended. One small issue: please remove the (xx) from the category > 1 month (see image below). Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c3de3575-f62d-4aee-9b7f-e5f4c7a36ed9)

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

I believe this issue should be resolved now in Production since my patches (included this typo correction) were deployed on Sep 23, 2021. This is the timing issue. Could you please kindly verify on Production region. Thank you.

**Comment by Travis-A-Clark** [comment]
@jp-Telus It looks like it's good in the Sys Admin view, but the HR Admin view and .CSV download still show the XX as part of the date. See screenshot below from Production this afternoon.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/e629463c-c994-4697-a0c0-54817c3be997)

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Thank you for verifying the program on Production. I figured that the changes was done for statistic report page under HRAdmin but not yet deploy on Production yet since I was bundle this fix with the #733 in some reason. #733 is waiting for the Prod migration. 

However, In fact, I have to update the excuse logic to adopt the table from Dennis command process. Should you move #733 to In process ? Thank you.

 

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/5e72e1b4-fe31-42c3-ba2a-9908d7940a1e)

**Comment by Travis-A-Clark** [comment]
PO approved. Rest of the work is on ticket #773.
