### ISSUE TITLE
As a System Admin I want to be able to assume other user ID's to assist in issue resolution

### ISSUE THREAD

**Issue by Abuchana** [bcgov/performance#80]
Will need a header similar to what the supervisor sees when they view an employee (i.e. You are now viewing Employee A's profile) to make it clear to the when they are acting as a different employee. Suggest wording: "You are now logged in as Employee A". See comments below for Phoebe's design.

**Comment by phoebesolomon** [comment]
![System Admin - Switch Identity Part 1.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/fb9952b6-7f53-4cc6-bd93-b6b207d50f59)

![System Admin - Switch Identity Part 2.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d30d9338-11a1-4fc2-97cb-7f44ec21faf1)

![System Admin - Switch Identity Part 3.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/943a6221-25d6-4147-9a8b-8f26354e88d9)

![System Admin - Switch Identity Part 4.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c78148bf-8df5-434d-8717-c6b3d0d9558b)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon Thanks for this! Can we just change the head from "You are viewing..." to "You are logged in as...".

Also, I will need to work with Dennis to standardize the search functionality at the top of all these screens. We have the org levels the same everywhere, but he and I need to discuss how many other fields to include.

**Comment by phoebesolomon** [comment]
@Travis-A-Clark revised! Re-uploaded the mockup above

**Comment by Travis-A-Clark** [comment]
@Kousthubha-M Dennis is working on the interface for all the Sys Admin pages, but I am hoping perhaps you can help set up the functionality for Sys Admin to be able to assume other users identities. It's similar concept to when supervisors view their employees profile, except that the Sys Admin can actually change the profile as the employee rather than view it and interact with it as themselves. We can chat more at our planning meeting this morning.

**Comment by Kousthubha-M** [comment]
@Travis-A-Clark I've pushed some changes related to this. This is not complete yet as this involves data linking and sync between users table and employee_demo table. I left notes to Dennis to take over from wherever I left. Thanks!

**Comment by jizhaogit** [comment]
Datatable and system message are applied.  waiting for deployment.

**Comment by Travis-A-Clark** [comment]
@jizhaogit I cannot currently see any content on this page other than the header. See screenshot below.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/34e3fe60-700d-42f0-a88a-7ba72a4ec267)

**Comment by jizhaogit** [comment]
Thanks Travis.  Dennis and i checked the changes history and addressed the blank page is cause by the recent page header update.  a new fixing is ready in repo.  will be deployed when Dennis has cycle.  thanks

**Comment by jizhaogit** [comment]
deployment done

**Comment by Travis-A-Clark** [comment]
@jizhaogit Thanks for this, Ji! A couple of things to address.

1) Can we update the switch identity search function to be consistent with all the other search functions for Sys Admin? The example below is from the "Share Employees" page. Are you able to copy and apply? I do like your solution of not loading any data until search criteria is entered so please keep that.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/0782c9b3-19ab-43b7-9f85-aa6105c9c150)

2) When I try to revert back to my original account, I sometimes get error messages depending on which screen I am on when I hit "revert". For example, below, I am logged in as Jennifer Erickson and have one of her goals open to edit.
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/bb6383ae-cab8-46a6-bd70-a03e365f54de)
When I click "Revert Identity" I get the error message below. I am guessing it is because my original user does not have access to edit that goal. Can we make it so that when you click "Revert Identity" you are always redirected to the home page of your own profile no matter what content you were looking at before?
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/a4527e23-0719-4354-84a9-04f65b966f7a)

**Comment by jizhaogit** [comment]
A new update is deployed in the repo, include:
1. user search UI update as request
2. redirect to dashboard page after "revert identity"
3. remove "revert identity" button from top right dropdown list to fix session bug

**Comment by jchow11** [comment]
@Travis-A-Clark @jizhaogit Found a hard-to-explain bug. I've made a video explaining how to reproduce:
https://www.loom.com/share/eb4c953afc534d5f86c64f085de182e7

### Changes
- [ ] Change verbiage in top banner "Logging in as" to "Logged in as"

- [ ] Ajax error message bug upon clicking "Back" in browser

**Comment by jizhaogit** [comment]
fix is pushed in the repo

**Comment by Travis-A-Clark** [comment]
@jizhaogit Hey, Ji! I am still getting the same bug and error message that Jordan mentioned before (see screenshot below). The user must hit "revert identity" to get back to their proper access. If they instead hit the back button, all of their permissions get messed up. Is there a way to fix this? Thanks!
<br>

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/8c903b44-996d-4dc2-8acf-563762d8eedd)

**Comment by jizhaogit** [comment]
It's because the route page was changed and the restriction control of switch identity was wrong.  i reverted back my changes and now it works.

Please note: we can not limit the "back" button of the browser. A Sys Admin user who switched their identity and hit the back button directly they will get back to the switch identity page.
