### ISSUE TITLE
Update title on authentication page

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#800]
Can we change "Performance Asystem" to "Performance Development Platform" on the log-in screen? Thanks!

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/8b3d0dd6-ab19-43f7-8318-52783793056f)

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

The issues was fixed by updating the "Keycloak Login Page Name" under Common Hosted Single Sign-on (CSS) website. 

https://bcgov.github.io/sso-requests

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/020a8cc4-bf87-414d-8ab0-999612afa700)

After update the name, the page was display correctly on all regions:

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/4f0d2713-4667-4cae-99e7-de8162de16d3)

Please kindly verify. Thanks

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

Per your request, the title is change to Performance Application Platform now on all regions:

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/cc5449b5-4d39-40a3-89ac-9e49490692d2)

**Comment by Travis-A-Clark** [comment]
@jp-Telus Sorry, was hoping for "Performance Development Platform".

Also, it appears that the log-in screen has gone weird on the Production site since this latest change:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/595ecb7e-1ce7-4fbc-bef5-8ed06d720579)

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

The followng issues were resolved now:
1) the title was changed to "Performance Development Plaffom"
2) the buttons were back to normal now, no idea why changed to 'link'.

![image.png](https://images.zenhubusercontent.com/60e73283e3a918390563e770/78e2f0c6-afe5-446c-9eb3-35bade294642)

**Comment by Travis-A-Clark** [comment]
@jp-Telus Name is correct everywhere (thanks!) but I still see weird formatting in the Production site. Test looks good, but Production is weird.

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/38c6d9f2-28c2-4a34-bf66-41da099658bd)

**Comment by Travis-A-Clark** [comment]
Turned out to be a caching issue in my version of Edge browser. Cleared cache and things display properly now. Ticket is complete.
